# Generated by Django 6.0.5 on 2026-05-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warmup', 'Warmup'), ('main', 'Main'), ('revision', 'Revision')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('image', 'Image'), ('list', 'List')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
